version: '3.8'

services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: trader_app_db
      MYSQL_USER: trader_app_user
      MYSQL_PASSWORD: trader_app_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trader_app_db
      SPRING_DATASOURCE_USERNAME: trader_app_user
      SPRING_DATASOURCE_PASSWORD: trader_app_password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
